config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  # You can have the root of your site routed with "root"
  root 'map#index'

  # Authorization
  devise_for :users, path: '', path_names: {
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'reset_password'
  }

  # Resources
  resources :statics
  resources :comments, only: [:create]

  resources :news do
    resources :comments
  end

  # API
  namespace :api, defaults: { format: :json } do
    get 'markers', to: 'markers#show'
  end

  # Admin
  namespace :admin do
    resources :news, except: [:show]
    resources :users, except: [:show]
    resources :pages, except: [:show]
    resources :comments, except: [:new, :create, :show]
  end

  get 'profile', to: 'users#profile'
  get 'profile/edit', to: 'users#edit'
  patch 'profile/update', to: 'users#update'

  match '/:url', url: /.*/, constraints: { url: /((?!assets)\w.+)+/ }, to: 'statics#display', via: :get
end

app/views/admin/pages/_form.html.erb
<%= form_for @page, url: @page.new_record? ? admin_pages_path : admin_page_path(@page) do |f| %>
  <% if @page.errors.any? %>
    <div class="alert alert-danger">
      <p>
        <strong>
          <%= "#{@page.errors.count} #{Russian.pluralize(@page.errors.count, 'ошибка', 'ошибки', 'ошибок')}:" %>
        </strong>
      </p>
      <ul>
        <% @page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :url, class: 'control-label' %>
    <div class="input-group">
      <span class="input-group-addon">http://<%= request.host %>/</span>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :html, class: 'control-label' %>
    <%= f.text_area :html, class: 'redactor' %>
  </div>

  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Редактирование страницы</h1>

<%= render 'form' %>

<%= link_to 'Просмотр', "/#{@page.url}", class: 'btn btn-warning' %>
<%= link_to 'К списку страниц', admin_pages_path, class: 'btn btn-default' %>

app/views/admin/pages/index.html.erb
<h1>Список страниц</h1>

<table class="table">
  <thead>
    <tr>
      <th>Название</th>
      <th>Адресс</th>
      <th width="160px"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.url %></td>
        <td>
          <%= link_to "/#{page.url}", target: '_blank' do %>
            <i class="fa fa-eye fa-fw"></i>Просмотр
          <% end %><br>

          <%= link_to edit_admin_page_path(page) do %>
            <i class="fa fa-pencil fa-fw"></i>Изменить
          <% end %><br>

          <%= link_to admin_page_path(page), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'text-danger' do %>
            <i class="fa fa-times fa-fw"></i>Удалить
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая страница', new_admin_page_path, class: 'btn btn-success' %>

app/views/admin/pages/new.html.erb
<h1>Новая страница</h1>

<%= render 'form' %>

<%= link_to 'К списку страниц', admin_pages_path, class: 'btn btn-default' %>