config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  # You can have the root of your site routed with "root"
  root 'map#index'

  # Authorization
  devise_for :users, path: '', path_names: {
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'reset_password'
  }

  # Resources
  resources :statics
  resources :comments, only: [:create]

  resources :news do
    resources :comments
  end

  # API
  namespace :api, defaults: { format: :json } do
    get 'markers', to: 'markers#show'
  end

  # Admin
  namespace :admin do
    resources :news, except: [:show]
    resources :users, except: [:show]
    resources :pages, except: [:show]
    resources :comments, except: [:new, :create, :show]
  end

  get 'profile', to: 'users#profile'
  get 'profile/edit', to: 'users#edit'
  patch 'profile/update', to: 'users#update'

  match '/:url', url: /.*/, constraints: { url: /((?!assets)\w.+)+/ }, to: 'statics#display', via: :get
end

app/views/partials/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-xs-6 col-md-6">
      <ul class="footer-nav">
        <li><a href="/wanna-post">Хотите публиковать?</a></li>
        <li><a href="http://warinukraine.reformal.ru" target="_blank">Отзывы и предложения</a></li>
        <li class="vkshare">
          <script type="text/javascript">
            document.write(VK.Share.button({
              url: 'http://warinukraine.info',
              title: 'Карта боевыйх действий в Украине 2014 год',
              description: 'Динамическая карта боевых действий и новостей происходящих в Украине, постоянно обновляется и улучшается.',
              image: 'http://warinukraine.info/images/WarInUkraine320x200.png'
            }));
          </script>
        </li>
      </ul>
    </div>
    <div class="col-xs-6 col-md-6 text-right">
      <p>War<strong>In</strong>Ukraine &copy; 2014</p>
      <a href="http://github.com/WarInUkraine/WarInUkraine" target="_blank"><i class="fa fa-github"></i> OpenSource</a>
    </div>
  </div>
</footer>

app/views/partials/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_CODE'] %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV['GOOGLE_ANALYTICS_CODE'] %>', '<%= ENV['GOOGLE_ANALYTICS_DOMAIN'] ||= 'warinukraine.info' %>');
    ga('send', 'pageview');
  </script>
<% end %>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="ukraine-ribbon"></div>
  <div class="container">
    <a href="/" class="navbar-brand">War<strong>In</strong>Ukraine</a>
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li<%= ' class=active' if params[:controller] == 'map' %>>
          <%= link_to 'Карта', root_path %>
        </li>
        <li<%= ' class=active' if params[:controller] == 'news' && params[:action] == 'index' %>>
          <%= link_to 'Новости', news_index_path %>
        </li>
        <li<%= ' class=active' if params[:controller] == 'news' && params[:action] == 'new' %>>
          <%= link_to 'Предложить новость', new_news_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.to_s %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Профиль', profile_path %></li>
              <% if current_user.admin? %>
                <li class="divider"></li>
                <li>
                  <li class="dropdown-header">Админ-панель</li>
                  <li><%= link_to 'Пользователи', admin_users_path %></li>
                  <li><%= link_to 'Новости', admin_news_index_path %></li>
                  <li><%= link_to 'Комментарии', admin_comments_path %></li>
                  <li><%= link_to 'Страницы', admin_pages_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>       
        <% else %>
          <li><a href="http://warinukraine.reformal.ru" target="_blank">Отзывы и предложения</a></li>
          <li><a href="/thanks">Благодарности</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>