config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  # You can have the root of your site routed with "root"
  root 'map#index'

  # Authorization
  devise_for :users, path: '', path_names: {
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'reset_password'
  }

  # Resources
  resources :statics
  resources :comments, only: [:create]

  resources :news do
    resources :comments
  end

  # API
  namespace :api, defaults: { format: :json } do
    get 'markers', to: 'markers#show'
  end

  # Admin
  namespace :admin do
    resources :news, except: [:show]
    resources :users, except: [:show]
    resources :pages, except: [:show]
    resources :comments, except: [:new, :create, :show]
  end

  get 'profile', to: 'users#profile'
  get 'profile/edit', to: 'users#edit'
  patch 'profile/update', to: 'users#update'

  match '/:url', url: /.*/, constraints: { url: /((?!assets)\w.+)+/ }, to: 'statics#display', via: :get
end

app/models/static.rb
class Static < ActiveRecord::Base
  # Validation
  validates :url, presence: true, uniqueness: true
  validates :title, presence: true
  validates :html, presence: true
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def display
    @static = Static.find_by_url!(params[:url])
    @page_title = @static.title
  end
end

app/views/statics/_form.html.erb
<%= form_for(@static) do |f| %>
  <% if @static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% @static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statics/display.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="static-page">
      <h1 class="static-page-title"><%= @static.title %></h1>
      <div class="static-page-html">
        <%= raw @static.html %>
      </div>
    </div>
  </div>
</div>

app/views/statics/edit.html.erb
<h1>Editing static</h1>

<%= render 'form' %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<h1>Listing statics</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Html</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statics.each do |static| %>
      <tr>
        <td><%= static.url %></td>
        <td><%= static.title %></td>
        <td><%= static.html %></td>
        <td><%= link_to 'Show', static %></td>
        <td><%= link_to 'Edit', edit_static_path(static) %></td>
        <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<h1>New static</h1>

<%= render 'form' %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @static.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @static.title %>
</p>

<p>
  <strong>Html:</strong>
  <%= @static.html %>
</p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>